codota/tabnine-vscode

src/extension.ts

Hey,
Thanks firstly for the tool + this plugin! I'm such a fan I made a license purchase last week :)
#12 was really frustrating me so I took a go at fixing it. Rather than use `args.position`, this uses `editor.selections` instead. It seems to do the trick based on my testing :)

Fix multi cursor

---

package-lock.json
src/extension.ts

- Substitute command was removed - the purpose of this command was to handle the cursor in case of new suffix suggested by tabnine, replacement of the old prefix and suffix, and position the cursor before the suggested new suffix for all selections. instead, [SnippetString](https://code.visualstudio.com/api/references/vscode-api#SnippetString) usage was added to the competition item creation (`makeCompletionItem`), which allows to add a literal template snippet that can handle the cursor position (`appendTabstop`) between the inserted text values .
- package-lock was updated due to deprecate usage of the flatmap-stream library (error while npm install : Not Found: flatmap-stream@https://registry.npmjs.org/flatmap-stream/-/flatmap-stream-0.1.0.tgz)
**after this fix:**

fix cursor position in case of suggested suffix

---

.gitignore

update binaries to 2.5.1

---

.gitignore
package.json

Issue/binaries 2.6.0

---

package-lock.json
package.json
src/extension.ts

tabnine config as vs code command

---

src/TabNine.ts
src/extension.ts

Adding the new `client-metadata` argument

adding client-metadata

---

src/importsHandler.ts

```
Button.ts
const Button = () => <button>hello</button>
export default Button
```
```
other.ts
<Button>
```

support import of default exports 

---

package-lock.json
package.json
src/extension.ts

user_messages moved to notification bar instead of completion details window
**before:
**
**after:**

onboarding - notifications

---

src/extension.ts
src/progressBar.ts
src/statusBar.ts

onboarding -  progress bar added, it will indicate the status of the model downloading progress

onboarding -  progress bar added

---

package-lock.json
package.json
src/TabNine.ts
src/commandsHandler.ts
src/configHandler.ts
src/extension.ts
src/notificationsHandler.ts
src/progressBar.ts
src/statusBar.ts

**in case of success(all good):**
**in case of any failure:**

TabNine - onboarding flow

---

src/TabNine.ts
src/extension.ts

handle the request timeout for getCapabilities request

handle the request timeout for getCapabilities request

---

src/TabNine.ts

this relevant for the first "getCapabilities" request that timed-outs after 1 second, i changed this request timeout to 5 seconds

parameterised timeout

---

package-lock.json
package.json
src/TabNine.ts
src/capabilities.ts
src/extension.ts
src/notificationsHandler.ts
src/progressBar.ts
src/statusBar.ts

fix multiple focus handling, reuse the on focus event for both capabilities and initialisation

fix multiple focus handling

---

src/commandsHandler.ts
src/configHandler.ts
src/extension.ts
src/notificationsHandler.ts

- completely removed the “internet connection error” message
- limited the “You had registered to TabNine Professional but didn’t enable the Deep Cloud” message to be shown only once
- all the “old” user notifications moved back to completion details window

1. completely removed the “internet connection error” message.

---

src/validator/ValidatorClient.ts
src/validator/ValidatorCodeActionProvider.ts
src/validator/ValidatorHandlers.ts
src/validator/diagnostics.ts
src/validator/utils.ts

* When closing vscode, validator binary stays alive - FIXED
* Added analytics for validator commands

Validator - more analytics

---

package-lock.json
package.json
src/TabNineExtensionContext.ts
src/autoImport.ts
src/binary/Binary.ts
src/binary/errorState.ts
src/binary/modelDownloadProgress.ts
src/binary/requests.ts
src/binary/requests/requests.ts
src/binary/requests/setState.ts
src/binary/run.ts
src/binary/state.ts
src/capabilities.ts
src/commandsHandler.ts
src/configHandler.ts
src/extension.ts
src/extensionContext.ts
src/handleUninstall.ts
src/provideCompletionItems.ts
src/selectionHandler.ts
src/semverUtils.ts
src/uninstall.ts
src/utils.ts
src/validator/ValidatorClient.ts
src/validator/ValidatorCodeActionProvider.ts
src/validator/ValidatorHandlers.ts
src/validator/cancellationToken.ts
src/validator/diagnostics.ts
src/validator/utils.ts
tsconfig.json

Also compile typescript to es2018 due to the fact that we target Node 10.x or higher. See: https://stackoverflow.com/a/57607634

Add Typescript Strict Mode

---

README.md
package.json

Update IDE SEO

---

src/statusBar/statusBar.ts
src/statusBar/stusBarActionHandler.ts

set state once for the same text

set state once for the same text

---

src/binary/requests/notifications.ts
src/notifications/pollNotifications.ts
src/test/suite/notification.test.ts

related to https://github.com/codota/acpl-paid/pull/385

notification message to action

---

src/binary/requests/notifications.ts
src/binary/requests/setState.ts
src/binary/requests/statusBar.ts
src/notifications/pollNotifications.ts
src/statusBar/stusBarActionHandler.ts
src/test/suite/notification.test.ts
src/test/suite/utils/testData.ts

related to https://github.com/codota/acpl-paid/pull/391

use notification_type API

---

dl_binaries.sh
package-lock.json
src/binary/fetchBinaryPath.ts

use binaries/.active file to select the version to run if such a file exists

---

src/alphaInstaller.ts
src/extension.ts
src/handleUninstall.ts
src/statusBar/statusBar.ts

clear alpha state on uninstall + show alpha version in status tooltip

clear alpha state on uninstall + show alpha version in status tooltip

---

src/capabilities.ts
src/commandsHandler.ts
src/consts.ts
src/extension.ts
src/notifications/pollNotifications.ts
src/statusBar/StatusBarData.ts
src/statusBar/statusBar.ts

Ref https://codota.atlassian.net/browse/DEV-1730
https://docs.google.com/document/d/1EGMYSsRUbFjZ_xrxqROoGWE2Rl6e09pkyygqeHiY5YY/edit

Increase VS Code Hub clicks experiment

---

package-lock.json
src/binary/binaryFetcher/bundleDownloader.ts
src/binary/binaryFetcher/existingVersionHandler.ts

handle published version validation

handle published version validation

---

src/binary/InnerBinary.ts
src/binary/requests/requests.ts
src/binary/requests/setState.ts
src/globals/consts.ts
src/selectionHandler.ts

upgrade api version to 3.5.34

---

package.json

this should solve the `ctrl+z` behavior on mac

fix keybind to support snippets

---

src/authentication/TabnineAuthenticationProvider.ts
src/authentication/TabnineSession.ts
src/authentication/authentication.api.ts
src/binary/state.ts
src/capabilities/capabilities.ts
src/extension.ts
src/globals/consts.ts

support tabnine authentication flow

support tabnine authentication flow

---

package.json
src/inlineSuggestions/textListener.ts
yarn.lock

Note: need to implement it on the proposed api branch too. The file in which I added the debounce is deleted completely in the proposed api branch.
(Also need to to take into consideration the fact the snippets are taking longer to fetch to begin with...)

feature: debounce empty lines request

---

.github/workflows/alpha_release.yml
.github/workflows/tag.yml
src/authentication/TabnineAuthenticationProvider.ts

apply modifier action

---

src/binary/requests/requests.ts
src/binary/requests/setState.ts
src/globals/consts.ts
src/inlineSuggestions/registerHandlers.ts
src/inlineSuggestions/tabnineInlineCompletionItem.ts
src/provideInlineCompletionItems.ts

The below issue has been solved by using the new api version 4.0.57
---
@dimacodota same as here: https://github.com/codota/tabnine-intellij/pull/263#issue-1101626578

add snippet shown event

---

package.json

add examples to color config

---

package.json
src/capabilities/capabilities.ts
src/extension.ts
src/globals/consts.ts
src/notificationsWidget/notificationsWidgetWebview.ts
src/tabnineTodayWidget/tabnineTodayWidgetWebview.ts
src/widgetWebview.ts
src/widgetWebview/WidgetWebviewProvider.ts
src/widgetWebview/widgetWebview.ts

Add stats to side bar with a webview

Add tabnine today sidebar

---

src/CompletionArguments.ts
src/binary/requests/requests.ts
src/binary/requests/setState.ts
src/globals/consts.ts
src/inlineSuggestions/registerHandlers.ts
src/inlineSuggestions/tabnineInlineCompletionItem.ts
src/provideInlineCompletionItems.ts
src/selectionHandler.ts

- add filename and intent to `SnippetShown`
- add intent to `AutocompleteResult` and to `SelectionRequest`

use api version 4.1.21

---

src/inlineSuggestions/hoverPopup.ts
src/inlineSuggestions/setInlineSuggestion.ts
src/inlineSuggestions/snippets/snippetDecoration.ts

debug context added for "inline" suggestion, will be triggered for alpha capability only

add debug context

---

package.json
src/binary/runBinary.ts
src/globals/tabnineExtensionProperties.ts

add log level settings property

---

src/binary/requests/completionPostProcess.ts
src/binary/requests/requests.ts
src/binary/requests/tabSize.ts
src/runCompletion.ts
src/test/suite/completionPostprocess/completionPostprocess.test.ts
src/test/suite/completionPostprocess/driver.ts

See the description on pr 1805 in our binary project for more details.

trim snippets with respect to indentation

---

src/capabilities/capabilities.ts
src/inlineSuggestions/registerHandlers.ts

remove the beta check and add an 'advanced completion' check

remove the beta check and add an 'advanced completion' check

---

src/inlineSuggestions/acceptInlineSuggestion.ts
src/inlineSuggestions/vimForVSCodeWorkaround.ts

https://tabnine.atlassian.net/browse/DEV2-565
I played with it, tried new line, mid line and end of line completions, and it seems to work well. Regarding tests - I'm looking into it, not entirely sure how to install the vim extension in the test environment.

Bug fix: Vim for VSCode mode switch on accept completion

---

src/autocompleteInstaller.ts
src/binary/Binary.ts
src/binary/mockedRunProcess.ts
src/capabilities/capabilities.ts
src/extension.ts
src/inlineSuggestions/registerHandlers.ts
src/test/suite/capabilities.test.ts

Support having the inline capabilities change affect immediately, without requiring a restart

Feature/enable completions UX change in realtime

---

src/CompletionArguments.ts
src/binary/requests/requests.ts
src/binary/requests/setState.ts
src/getAutoImportCommand.ts
src/globals/consts.ts
src/inlineSuggestions/tabnineInlineCompletionItem.ts
src/lookAheadSuggestion.ts
src/provideInlineCompletionItems.ts
src/selectionHandler.ts
src/test/suite/utils/completion.utils.ts

bump api version - snippet_context usage
ref https://github.com/codota/acpl-paid/pull/2071

bump api version - snippet_context usage

---

src/lookAheadSuggestion.ts

call selection command when inline suggestion is selected and the popup is visible

call selection command when inline suggestion is selected

---

src/inlineSuggestions/documentChangesTracker/DocumentTextChangeContent.ts
src/test/suite/completion.test.ts

this is a more generic fix  for https://github.com/codota/tabnine-vscode/pull/968
it handles space indentation as well

Dev2 1677 tab  indent fix for first tab

---

src/lookAheadSuggestion.ts

wrong check for retry fulfillment

wrong check for retry fulfillment

---

src/binary/requests/requests.ts
src/test/suite/utils/testData.ts

Reverts codota/tabnine-vscode#994 - **except for the test fix**
reverted binary changes as well

DEV2-1924: Revert "prompt additional properties"

---

src/binary/runBinary.ts
src/globals/tabnineExtensionProperties.ts

check for editor.inlineSuggest.enabled

DEV2-2085 check for editor.inlineSuggest.enabled

---

.github/workflows/bump_version.yml
package.json

DEV2-2087 setup git before npm version

DEV2-2087 setup git before npm version

---

src/CompletionArguments.ts
src/binary/requests/requests.ts
src/binary/requests/suggestionShown.ts
src/getAutoImportCommand.ts
src/getInlineCompletionItems.ts
src/globals/consts.ts
src/inlineSuggestions/hoverPopup.ts
src/inlineSuggestions/setInlineSuggestion.ts
src/lookAheadSuggestion.ts
src/provideCompletionItems.ts
src/reportSuggestionShown.ts
src/selectionHandler.ts
src/test/suite/utils/completion.utils.ts
src/test/suite/utils/testData.ts

exactly the same changes as here: https://github.com/codota/tabnine-intellij/pull/462

DEV2-2022 use new api version 4.4.223

---

src/testgen/TestGenCodeLensProvider.ts
src/testgen/generateTests.ts

DEV2-2328 - code -gen fixes

---

src/testgen/TabnineCodeLens.ts
src/testgen/TestGenCodeLensProvider.ts

DEV2-2328 - fix copy

---

src/globals/consts.ts
src/runCompletion.ts

similar to the IJ behavior - https://github.com/codota/tabnine-intellij/blob/7a0bd09aaa706890bcbf368f9599e9eff9b5abc1/Common/src/main/java/com/tabnineCommon/prediction/CompletionFacade.java#L114

DEV2-2855 - increase TO of new line requests

---

src/debounceCompletions.ts
src/getInlineCompletionItems.ts
src/test/suite/completion.test.ts

DEV2-2856 - refetch suggestions on idle

DEV2-2856 - refetch suggestions on idle

---

src/preRelease/installer.ts
src/preRelease/types.ts
src/test/suite/utils/preReleaseInstaller.utils.ts

DEV2-2875 fix alpha release

---

src/enterprise/requests/UserInfo.ts
src/enterprise/statusBar/StatusBar.ts
src/enterprise/statusBar/StatusItem.ts
src/enterprise/statusBar/statusAction.ts

DEV2-2812 part of the team indication

DEV2-2812 part of the team indication

---

.github/workflows/tag.yml

DEV2-2894  fix slack message

---

src/tabnineChatWidget/handlers/getEditorContextHandler.ts

DEV2-2966 improve diagnostics text

DEV2-2966 improve diagnostics text

---

src/enterprise/statusBar/statusAction.ts

the `[ ]` is a typo, this why it isn't working

DEV2-3027: Open the settings in the extention settings

---

src/binary/binaryFetcher/activeFileHandler.ts
src/binary/binaryFetcher/binaryValidator.ts
src/binary/binaryFetcher/existingVersionHandler.ts
src/test/suite/invalidVersions.test.ts

[DEV2-3062](https://tabnine.atlassian.net/browse/DEV2-3062)
[DEV2-3062]: https://tabnine.atlassian.net/browse/DEV2-3062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEV2-3062 - filterinvalid versions

---

src/enterprise/extension.ts
src/enterprise/statusBar/statusAction.ts
src/enterprise/update/updateAndReload.ts
src/extension.ts
src/utils/logger.ts

DEV2-2085 support show logs

---

package.json

Loads extension after start up is finished instead of on VS Code start up

---

src/binary/requests/fileMetadata.ts

DEV2-3312 fix missing metadata failure

DEV2-3312 fix missing metadata failure

---

.github/workflows/alpha_release.yml
.github/workflows/bump_version.yml

DEV2-3410 disable alpha release

DEV2-3410 disable alpha release

---

README.md

MAR-199 - remove discord/slack

---

package.json

DEV2-3600 bump version to 3.8.12

---

README.md

remove 💡  (":bulb:") emoji that doesn't look good on the vscode marketplace

DEV2-3640 - fix "Note:" header

---

.github/workflows/bump_version.yml

DEV2-3671 bump minor on release

DEV2-3671 bump minor on release

---

src/activeTextEditorState.ts
src/binary/requests/prefetch.ts
src/extension.ts

Notify binary on active text editor change

DEV2-3664: active-text-editor

---

src/enterprise/consts.ts
src/enterprise/extension.ts
src/globals/tabnineExtensionProperties.ts

if the user disabled the proxy setting in the updater, we should use this setting

DEV2-3822: Copy disable proxy setting from updater

---

src/tabnineChatWidget/ChatApi.ts
src/tabnineChatWidget/EventRegistry.ts

For now, it will return `https://api.tabnine.com` as default.  in the future it will ask the binary for that

DEV2-3856: Add command to get the server URL

---

package.json
src/tabnineChatWidget/ChatViewProvider.ts
src/tabnineChatWidget/tabnineChatWidgetWebview.ts

https://github.com/codota/tabnine-vscode/assets/10290661/5684da81-938c-4971-85c0-7133d8de4291

DEV2-3884: add right-click actions for chat

---

src/tabnineChatWidget/ChatApi.ts
src/tabnineChatWidget/handlers/navigateToLocation.ts

https://github.com/codota/tabnine-vscode/assets/67855609/fd98b657-cabf-4a17-85a6-96929db2589c

DEV2-4120 add "navigate_to_location" handler

---

.github/workflows/continues_integration.yml
src/authentication/authentication.api.ts
src/binary/Binary.ts
src/enterprise/consts.ts
src/enterprise/extension.ts
src/globals/tabnineExtensionProperties.ts
src/proxyProvider.ts
src/utils/notifyOnError.ts

DEV2-4252 trim trailing proxy url backslash

DEV2-4252 trim trailing proxy url backslash

---

src/WorkspaceUpdater.ts
src/binary/requests/workspace.ts
src/enterprise/extension.ts
src/extension.ts
src/globals/consts.ts
src/tabnineChatWidget/ChatApi.ts
src/workspaceUpdater.ts

https://github.com/codota/tabnine-vscode/assets/67855609/a0982345-3790-4899-bbcd-83d9821cc01c

DEV2-4225 support multi workspace in retrieval-related features

---

src/tabnineChatWidget/extensionCommands/codeLens/ChatCodeLensProvider.ts
src/tabnineChatWidget/extensionCommands/codeLens/index.ts

DEV2-4266 fireevent on command

DEV2-4266 fireevent on command

---

src/tabnineChatWidget/extensionCommands/codeLens/ChatCodeLensProvider.ts
src/tabnineChatWidget/extensionCommands/codeLens/index.ts

DEV2-4301 - add document lens, remove fix if no diagnostics
-  add  "document" code lens
- file the "fix" lens  if there are no diagnostics in the range

DEV2-4301 - add document lens, remove fix if no diagnostics

---

src/tabnineChatWidget/extensionCommands/codeLens/ChatCodeLensProvider.ts

DEV2-4343 do not send on visited file

DEV2-4343 do not send on visited file

---

src/WorkspaceUpdater.ts

DEV2-4390 fix workspace paths on windows

---

src/enterprise/consts.ts
src/enterprise/extension.ts
src/globals/consts.ts
src/globals/tabnineExtensionProperties.ts

DEV2-4433 move enterprise config

DEV2-4433 move enterprise config

---

src/languages/java/JavaHome.ts

DEV2-4448 do not fail on  missing sdk

DEV2-4448 do not fail on  missing sdk

---

package.json
src/capabilities/capabilities.ts
src/extension.ts
src/tabnineChatWidget/ChatEnabledState.ts
src/tabnineChatWidget/SaasChatEnabledState.ts
src/tabnineChatWidget/webviews/previewEnded.html.ts
src/tabnineChatWidget/webviews/previewEndedView.ts

DEV2-4419: enable chat for preview users

---

.github/workflows/tmp.yml

DEV2-4348  temp vars
