src/extension.ts
- escape $ sign that is preserved for tab stops in snippet strings.
- remove the tabstop if there is no suffix - otherwise it will mark the text after the inserted snippet as selected.
**first issue:**
**second issue:**
=> escape $ sign that is preserved for tab stops in snippet strings and remove the tabstop if there is no suffix

src/extension.ts
fix tab stop to end the selection after the first stop, this is an vscode issue: https://github.com/microsoft/vscode/issues/43270\#issuecomment-430624161
**before the fix:**
**after the fix:**
=> fix snippet text selection

src/TabNine.ts
VS Code's 32-bit build on Windows is built against ia32, not x32. Therefore, prior to this change, TabNine unconditionally and silently failed to work on 32-bit VS Code.
=> Add ia32 to 32-bit-compatible architectures

src/capabilities/capabilities.ts, src/extension.ts, src/globals/consts.ts, src/provideCompletionItems.ts
if the user chooses to allow empty line completions (will be added in the hub soon) - trigger vscode's completion popup upon `\n`
=> imporve empty line completions experience

src/inlineSuggestions/registerHandlers.ts, src/inlineSuggestions/snippets/snippetProvider.ts
1. Snippets are not deleted upon backspace
2. If you request a snippet in file a and then switch to file b - the snippet are appearing in the new location (file b). It happens because snippets are taking long to retrieve (1-2 sec).
Note: We do have a listener that clears the state upon cursor move, but its not triggered if you switch between files w/o moving the cursor.
1.  in `src/inlineSuggestions/registerHandlers.ts` - `e.kind === undefined` is true when the change is backspace, so not ignoring it and clearing the state in such cases. Its also true when the snippet blank space is being inserted, hence the `!isInSnippetInsertion()` check.
2. in `src/inlineSuggestions/snippets/snippetProvider.ts` - after retrieving snippet completions, check if the current file matches the file in which …
=> improve snippets behaviour

src/capabilities/capabilities.ts, src/extension.ts, src/globals/consts.ts, src/inlineSuggestions/inlineSuggestionState.ts, src/inlineSuggestions/positionExtracter.ts, src/inlineSuggestions/registerHandlers.ts, src/inlineSuggestions/setInlineSuggestion.ts, src/inlineSuggestions/snippets/autoTriggerHandler.ts, src/inlineSuggestions/snippets/snippetProvider.ts, src/inlineSuggestions/textListener.ts, src/provideCompletionItems.ts
If `EMPTY_LINE_SUGGESTIONS` capability is enabled, provide inline suggestions on empty lines
1. Move empty lines logic from `provideCompletionIterms.ts` (popup completions) to `textListener.ts` (inline completions)
2. Add `CompletionType` to `inlineSuggestionState.ts` to differentiate between snippet completions and inline completions - previously was done by checking if the completion contains more than one line, which is a weaker way to get this information.
3. extract `getCurrentPosition` to a new file, allowing both snippet and regular completions to use the same function to determine a `Position` from `TextDocumentContentChangeEvent`. While I was playing around with the logic of this function to support empty lines, it came out as just what was needed to unify snippets and regular …
=> feature: empty lines -> inline completions

src/inlineSuggestions/snippets/snippetDecoration.ts
Currently, when a snippet hint is displayed and the user types something, it gets deleted along with the snippet hint's disappearance. It happens because we delete the `snippetBlankRange` which starts where the user requested a snippet, and not where they are now (when deleting the hint)
When deleting the hint, calculate the difference between the position in which the user requested a snippet and the position in which they are now. Delete the only difference between the original `snippetBlankRange` and the new position.
https://user-images.githubusercontent.com/67855609/141697300-7a55b0b7-34bf-4b7e-97ab-379f652db0a0.mp4
=> fix snippet clear hint bad behaviour

src/binary/requests/requests.ts, src/inlineSuggestions/inlineSuggestionState.ts, src/inlineSuggestions/setInlineSuggestion.ts, src/inlineSuggestions/snippets/snippetDecoration.ts, src/inlineSuggestions/snippets/snippetProvider.ts, src/inlineSuggestions/textListener.ts
We're trying to smoothly integrate snippets as part of your regular tabnine experience, which requires a lot of things (outside the scope of this pr).
- Use `CompletionKind` to determine whether the current inline hint is a snippet or a regular one - this allows to have a state with both types of completions and move between them smoothly
- Removed an old `if` statement in `src/inlineSuggestions/textListener.ts` that's turned out to be redundant:
The code was suppose to clear the inline hint in case the text has changed and you don't want to show a new hint. This is being handled by our cursor listener - a changed text also moves the cursor.
- Fix snippet hint deletion upon cursor move - in my previous fixes I caused a problem where if you move your cursor while a snippet hint is being …
=> snippets improvements

src/inlineSuggestions/clearDecoration.ts, src/inlineSuggestions/registerHandlers.ts, src/inlineSuggestions/setInlineSuggestion.ts, src/inlineSuggestions/snippets/acceptSnippetSuggestion.ts, src/inlineSuggestions/snippets/autoTriggerHandler.ts, src/inlineSuggestions/snippets/blankSnippet.ts, src/inlineSuggestions/snippets/snippetDecoration.ts, src/inlineSuggestions/snippets/snippetProvider.ts, src/inlineSuggestions/textListener.ts, src/test/suite/blankSnippet.test.ts, src/test/suite/index.ts, src/test/suite/snippetBlank.test.ts, src/test/suite/utils/inline.utils.ts
A follow up to #694
Until now, snippets handling was heavily relying on the assumption that snippets will only be shown on newlines. This assumption must break in order to merge snippet completions with regular ones.
1. Extract snippets blank range logic to `blankSnippet.ts`, and make it differentiate between blank insertion on empty vs. non empty lines:
On empty lines it works the same, but for non empty lines it inserts the blank range one line **below** the current position (because we want to present part of the hint in the current line), and then move the cursor back to the correct position.
2. Touch-ups to `src/inlineSuggestions/snippets/snippetDecoration.ts` (where the snippet hint is being constructed) to make it work for both empty and non empty lines.
3. Change …
=> feature: make snippets work on non empty lines

src/extension.ts, src/globals/versions.ts
check the minimal [`registerAuthenticationProvider`](https://code.visualstudio.com/updates/v1_54#_authentication-provider-api) version.  this api was supported in the  [1.54](https://code.visualstudio.com/updates/v1_54) version
=> fix: check minimal authentication provider api version

src/binary/state.ts, src/statusBar/StatusBarData.ts, src/statusBar/statusBar.ts
need to show "tabnine team" for paid customers, but show "tabnine pro" for legacy pro + students
=> repackaging feb22 - show 'tabnine team' in statusbar

src/inlineSuggestions/registerHandlers.ts
**problem:**  
the `provideInlineCompletionItems` is imports  he  `TabnineInlineCompletionItem` witch imports the `TabnineInlineCompletionItem` that extends from  the `InlineCompletionItem` that does not exists below 1.53.0 version
**solution:**  
conditionally import  the `provideInlineCompletionItems` after the supported version check is done
=> conditionally import provideInlineCompletionItems

src/capabilities/capabilities.ts
in order to catch binary config changes in somewhat "real time", we shorten the interval between capabilities refresh
=> refresh capabilities more often

package.json, src/getAutoImportCommand.ts, src/globals/consts.ts, src/inlineSuggestions/registerHandlers.ts, src/inlineSuggestions/tabnineInlineCompletionItem.ts, src/lookAheadSuggestion.ts, src/provideInlineCompletionItems.ts, src/test/suite/completion.test.ts, src/test/suite/utils/completion.utils.ts, src/test/suite/utils/helper.ts, src/test/suite/utils/testData.ts
**motivation**: in the case where both a popup and the inline are visible, 'tab` key selects the popup suggestion:
**solution**: 
this pr adds the following : 
- `lookahead` mode(the code was extracted on moved to a new file) - in this mode tabnine extends the selected  popup item and suggests a longer inline suggestion
- the current `lookahead` suggestion is stored
- we override the `tab` key and check if there is an active `lookahead` suggestion and accept it if any and fallback to the regular acceptance logic if there is no active `lookahead` suggestion
**before this fix**:
https://user-images.githubusercontent.com/60742964/178226600-da3a9a43-d2af-4432-8d58-bbf07f4389bb.mov 
**after this fix**:
https://user-images.githubusercontent.com/60742964/178226594-18e62b6c-e39c-461e-b175-ab89724d …
=> override tab key for inline

package.json, src/inlineSuggestions/hintColor.ts, src/inlineSuggestions/setInlineSuggestion.ts, src/inlineSuggestions/snippets/snippetDecoration.ts
since we're using vscode's inline completions API we no longer control the color of the hint - so this settings property has no effect on the users.
=> remove inline hint color settings

src/lookAheadSuggestion.ts, src/test/suite/completion.test.ts
The issue:
In the case where both inline and popup are visible and inline is accepted, the accepted text is marked as selected after selection, so any change will remove the selected area
before:
after:
=> fix the selected text when an inline suggestion is selected and the popup is visible

src/lookAheadSuggestion.ts
fix for the following use case:
- user is typing dot (".")
- vscode shows completions (inside the popup) that don't start with "."
- the user focuses on one of those suggestions
- the SelectedCompletionInfo text contains that dot at the beginning of the completion
- we are filtering completions that have the same prefix as the SelectedCompletionInfo text, but don't find any. (since "use" != ".use")
- the user doesn't get any completion
the fix is to pass the SelectedCompletionInfo text to the filter function without the dot
=> fix lookAhead dot but

src/inlineSuggestions/documentChangesTracker/DocumentTextChangeContent.ts, src/inlineSuggestions/documentChangesTracker/index.ts
**Problem:** 
in some cases, the onDidChangeTextDocument callback is raised with multiple contentChanges causing the current change to be filtered and thus not triggering any request in this position.
**Solution:** 
the array should be filtered by the current cursor position.
=> filter the relevant change by the current position

src/provideInlineCompletionItems.ts, src/test/suite/completion.test.ts, src/test/suite/utils/completion.utils.ts, src/test/suite/utils/helper.ts, src/test/suite/utils/testData.ts
**problem:** 
in some cases, the binary  returns multiline `old_suffix` which is probably another issue that should be investigated
the solution in this pr is to modify the [replace range](https://github.com/codota/tabnine-vscode/blob/a12abaf4d511c67d1af69bdc9692995a12c0619f/src/vscode.proposed.inlineCompletions.d.ts#L105) only in case of a single  line which  should handle closing brackets that should be replaced
=> Dev2-1649 wrong indentation in case of multine old suffix

src/binary/requests/tabSize.ts, src/inlineSuggestions/documentChangesTracker/DocumentTextChangeContent.ts, src/test/suite/completion.test.ts, src/test/suite/utils/completion.utils.ts
**problem:**
in the case of "tab" indentation (`\t`), the change detection was expecting only spaces `" "` and not tab indentation
=> DEV2-1677 check for tab-in in languages with tab indentation vs. spaces

src/inlineSuggestions/documentChangesTracker/DocumentTextChangeContent.ts
in some cases, the first indentation tab will fire with "range to replace" =  1 and change = "\t\t" meaning it would replace the existing one tab with 2
=> DEV2-1677 fix tab-indent for first tab

src/lookAheadSuggestion.ts
the order is handled by Tabnine engine(binary), the returned suggestions are ordered by the probability + length, so there is no need to reorder them, the only thing that should be handled is prefix matching.
ref https://tabnine.atlassian.net/browse/DEV2-1254
=> DEV2-1254 do not change the order of the suggestions

src/inlineSuggestions/documentChangesTracker/DocumentTextChangeContent.ts, src/inlineSuggestions/documentChangesTracker/index.ts, src/test/suite/completion.test.ts
the purpose of this pr is to enable suggestions for "indentation-out" (backspace) this is relevant manly in python 
before the fix:
after the fix:
=> Dev2 1539 - support indentation-out  backspace change

src/enterprise/statusBar/StatusBar.ts
do not prompt the user to use "tabnine enterprise" session on startup
=> DEV2-2884 do not require session by default

src/enterprise/requests/UserInfo.ts, src/enterprise/statusBar/StatusBar.ts
check if the user is logged in via the `UserInfo` request instead of the `authentication.getSession` which is inited later
=> DEV2-2907 fix login notification raise

src/enterprise/extension.ts, src/enterprise/statusBar/StatusBar.ts, src/enterprise/update/serverUrl.ts
From the code (and testing), it seems that the user doesn’t actually need to set it twice because it is looking at the other value as well. But if the user clicks on the settings, the cloud URL seems empty. So we will copy the settings if not set (so we won't override it)
=> DEV2-3026: Copy configuration from updater extension

package.json
Extension was failing to initialize correctly when launched in [devcontainers](https://code.visualstudio.com/docs/devcontainers/containers). Upon investigating, it appears that users needed to manually input certain settings to workaround this issue.
To enable the Tabnine extension to work with devcontainers, users [have been required to add the following settings](https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location) to their VSCode settings.json:
```jsonc
// VSCode user's settings.json
{
"remote.extensionKind": {
"TabNine.tabnine-vscode": [
"ui",
"workspace"
]
}
}
```
Considering the complexity and inconvenience this imposes on users, I've prepared this PR to address and resolve the issue.
=> DEV2-3247 - Fix: Startup Issue in devcontainers

src/enterprise/extension.ts
This PR makes the updater/self hosted extension which is `tabnine-vscode-self-hosted-updater` to remove both GA and the now deprecated enterprise extnsion
=> DEV2-3537: Remove all other extensions that user might have

src/globals/tabnineExtensionProperties.ts
for the e2e eval - i need to see the binary logs to debug what's going on there, so the e2e eval will pass these env args and upload the log file
=> DEV2-4342 log file and level from env

src/WorkspaceUpdater.ts, src/capabilities/capabilities.ts, src/tabnineChatWidget/ChatApi.ts, src/utils/workspaceFolders.ts
this pr also removes the `WORKSPACE_TRACE` capability
=> DEV2-4390 add getWorkspaceRootPaths util

src/enterprise/extension.ts, src/globals/consts.ts, src/tabnineChatWidget/ChatApi.ts
this line from the CI fails the build: 
[`test "$(cat temp/extension/out/extension.js | grep tabnine.enterprise | wc -l)" = "0"`](https://github.com/codota/tabnine-vscode/blob/03d842eb384a3a9b3af3410a9fc7a1c9304986a4/.github/workflows/tag.yml#L69) 
because I added `"tabnine.enterprise"` to the non-enterprise plugin in this line:
[`isSelfHosted: context.workspaceState.get(TABNINE_ENTERPRISE_KEY, false),`](https://github.com/codota/tabnine-vscode/blob/03d842eb384a3a9b3af3410a9fc7a1c9304986a4/src/tabnineChatWidget/ChatApi.ts#L125) 🤦🏻 
change the key that's used in the non-enterprise plugin to `tabnine.isSelfHosted` 🤦🏻 
I built the extension locally from this branch and ran the line from the CI:
```
➜  tabnine-vscode git:(DEV2-4342-fix-release) ✗ test "$(cat temp/extension/out/extension.js | …
```
=> DEV2-4342 fix tabnine.enterprise key

src/enterprise/consts.ts, src/enterprise/extension.ts, src/extension.ts, src/globals/consts.ts, src/tabnineChatWidget/ChatApi.ts, src/tabnineChatWidget/ChatViewProvider.ts, src/tabnineChatWidget/chatEventRegistry.ts, src/tabnineChatWidget/tabnineChatWidgetWebview.ts
DEV2-4433 chat api usage
highlights:
the chat api is now a class that exposes 
- the handle Message api 
- handles the chat incoming requests
this class is inited differently from the saas extension and the enterprise extension
=> DEV2-4433 chat api usage

src/binary/runBinary.ts, src/globals/tabnineExtensionProperties.ts
check if intellicode is running to avoid collision
=> DEV2-4455 - check if intellicode is running to avoid collision

src/authentication/TabnineAuthenticationProvider.ts
I've recently noticed an issue with the tabnine extension in [Eclipse Theia](https://github.com/eclipse-theia/theia), see https://github.com/eclipse-theia/theia/issues/13336. I've tracked the issue down to a call to [`getState`](https://github.com/msujew/tabnine-vscode/blob/80ec9493f32dcc95d0a8abeaca124f2a31e25388/src/binary/requests/requests.ts#L113-L117), which incorrectly fires the auth session change event, even though no login information has changed (some other, state related information changed, but the auth info was the same). I couldn't figure out why the extension behaves differently in vscode vs Theia, since both send the exact same events to the extension.
Instead, this change prevents the session change event from firing in case the access token didn't change. I've confirmed …
=> Check access token before firing auth change event
